#!/bin/bash

# I'm using this script to reprocess log data for a specific robot, to make a map

# This scripts is for bringing up a ground station
#if [ "$EUID" -ne 0 ]
#  then echo "please run as root"
#  exit
#fi

function cleanup {

    echo "Stopping procman controller"
    killall procman-controller
    echo "Stopping procman daemon"
    killall procman-daemon

    wait $daemon
    wait $controller

    exit
}
trap cleanup SIGINT

export ROBOT_ID=7
export ROOT=$(readlink -f $(dirname $0)/..)
export MAGIC2="$ROOT/magic2"
echo "Using MAGIC2=$MAGIC2"

export PATH=$PATH:$ROOT/bin
export LCMTYPES=""
export LCMTYPES="$LCMTYPES $ROOT/lcmtypes/"
export LCMTYPES="$LCMTYPES $MAGIC2/lcmtypes/"
export LCMTYPES="$LCMTYPES $MAGIC2/../navboard/lcmtypes/"
export LCMTYPES="$LCMTYPES $MAGIC2/april2/lcmtypes/"
export APRIL2_PATH="$MAGIC2/april2"

# generate config files for reprocessing robot data# Concatenate generic and per-robot configs
echo "//THIS IS AUTO AN AUTOGENERATED FILE, MODIFICATIONS WILL BE OVERWRITTEN" > $ROOT/config/proc-robot-concat.config
cat $ROOT/config/proc-robot-gen.config >> $ROOT/config/proc-robot-concat.config

if [ -f $ROOT/config/proc-robot-$ROBOT_ID.config ]
then
    cat $ROOT/config/proc-robot-$ROBOT_ID.config >> $ROOT/config/proc-robot-concat.config
else
    echo "WARNING, NO PER-ROBOT PROCMAN FILE FOUND $ROOT/config/proc-robot-$ROBOT_ID.config"
fi

echo "//THIS IS AUTO AN AUTOGENERATED FILE, MODIFICATIONS WILL BE OVERWRITTEN" > $ROOT/config/robot-concat.config
cat $ROOT/config/robot-gen.config >> $ROOT/config/robot-concat.config

if [ -f $ROOT/config/robot-$ROBOT_ID.config ]
then
    echo "APPENDING $ROOT/config/robot-$ROBOT_ID.config"
    cat $ROOT/config/robot-$ROBOT_ID.config >> $ROOT/config/robot-concat.config
else
    echo "WARNING, NO PER-ROBOT CONFIG FILE FOUND $ROOT/config/robot-$ROBOT_ID.config"
fi


# Network setup
#ifconfig eth0 10.0.1.1 netmask 255.255.255.0
#route add -net 224.0.0.0 netmask 240.0.0.0 dev eth0
#route add -net 10.0.0.0 netmask 255.255.0.0 gw 10.0.1.2 dev eth0

# LCM Happiness w/o internet
# ifconfig lo multicast
# route add -net 224.0.0.0 netmask 240.0.0.0 dev lo

(procman-daemon) &
daemon=$!
(procman-controller -c $ROOT/config/proc-gnd.config) &
controller=$!

printf "HomePage: \033[1mhttp://localhost:3912\033[m\n"

wait $daemon
wait $controller

#while true; do
#    : # Do nothing
#done
